//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuidanceConsultancy.Models.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DishaGuidanceEntities : DbContext
    {
        public DishaGuidanceEntities()
            : base("name=DishaGuidanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mst_Class> Mst_Class { get; set; }
        public virtual DbSet<Mst_Gender> Mst_Gender { get; set; }
        public virtual DbSet<Mst_Login> Mst_Login { get; set; }
        public virtual DbSet<Mst_Norms> Mst_Norms { get; set; }
        public virtual DbSet<Mst_Performance> Mst_Performance { get; set; }
        public virtual DbSet<Mst_Role> Mst_Role { get; set; }
        public virtual DbSet<Mst_School> Mst_School { get; set; }
        public virtual DbSet<Mst_SchoolMedium> Mst_SchoolMedium { get; set; }
        public virtual DbSet<Mst_SchoolType> Mst_SchoolType { get; set; }
        public virtual DbSet<Mst_Student> Mst_Student { get; set; }
        public virtual DbSet<Mst_SubTest> Mst_SubTest { get; set; }
        public virtual DbSet<Student_Graph> Student_Graph { get; set; }
        public virtual DbSet<Student_Pdf> Student_Pdf { get; set; }
        public virtual DbSet<Student_Result> Student_Result { get; set; }
    }
}
