//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuidanceConsultancy.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Norms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mst_Norms()
        {
            this.Student_Result = new HashSet<Student_Result>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> SchoolTypeId { get; set; }
        public Nullable<int> SubTestId { get; set; }
        public Nullable<int> MinRange { get; set; }
        public Nullable<int> MaxRange { get; set; }
        public Nullable<int> StenScore { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Mst_Class Mst_Class { get; set; }
        public virtual Mst_SchoolType Mst_SchoolType { get; set; }
        public virtual Mst_SubTest Mst_SubTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Result> Student_Result { get; set; }
    }
}
