//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuidanceConsultancy.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mst_Login()
        {
            this.Mst_Student = new HashSet<Mst_Student>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Pwd { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual Mst_Role Mst_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mst_Student> Mst_Student { get; set; }
    }
}
