//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuidanceConsultancy.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mst_Student()
        {
            this.Student_Graph = new HashSet<Student_Graph>();
            this.Student_Pdf = new HashSet<Student_Pdf>();
            this.Student_Result = new HashSet<Student_Result>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public string ContactNo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public string Suggestions { get; set; }
        public string EmailId { get; set; }
    
        public virtual Mst_Class Mst_Class { get; set; }
        public virtual Mst_Gender Mst_Gender { get; set; }
        public virtual Mst_Login Mst_Login { get; set; }
        public virtual Mst_School Mst_School { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Graph> Student_Graph { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Pdf> Student_Pdf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Result> Student_Result { get; set; }
    }
}
