//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuidanceConsultancy.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Graph
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string GraphImagePath { get; set; }
    
        public virtual Mst_Student Mst_Student { get; set; }
    }
}
